---
## Set up cron jobs to collect backups
- name: Ensure backups path exists
  become_user: "{{ os_user }}"
  file: path={{ diaspora_home }}/backups mode=0750 state=directory

- name: Install backups scripts
  become_user: "{{ os_user }}"
  template: dest={{ diaspora_home }}/prepare_diaspora_backups.sh src=prepare_diaspora_backups.sh.j2 mode=0750

- name: Set cron for backup script execution
  cron: backup=yes hour=6 minute=10 name="diaspora_{{ os_user }}_db_backup" state=present user=root job="{{ diaspora_home }}/prepare_diaspora_backups.sh"
