---
- name: Ensure github.com is a known host
  lineinfile:
    dest: "{{ diaspora_home }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    backup: yes
  become: yes
  become_user: "{{ os_user }}"

- name: Clone source
  git: dest={{ diaspora_home }}/diaspora accept_hostkey=yes force=yes repo=https://github.com/{{ repository }}.git version={{ branch }}
  become: yes
  become_user: "{{ os_user }}"
